[package]
name = "order-manager"
version = "4.0.1"
authors = ["Sebastian Rollen <seb@overmu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpaca = {git = "ssh://git@github.com/Overmuse/alpaca.git", tag = "v0.7.0", default-features = false, features = ["rest", "ws"]}
anyhow = "1.0.39"
chrono = "0.4.19"
config = "0.10.1"
dotenv = "0.15.0"
futures = "0.3.15"
kafka-settings = {git = "ssh://git@github.com/Overmuse/kafka-settings.git", tag = "v0.3.1" }
multimap = "0.8.3"
num-traits = "0.2.14"
position-intents = {git = "ssh://git@github.com/Overmuse/position-intents.git", tag = "v0.6.0" }
rdkafka = { version = "0.26.0", features = ["ssl-vendored"] }
rust_decimal = "1.14.1"
serde = "1.0.124"
serde_json = "1.0.64"
serde_plain = "0.3.0"
sqlx = {version = "0.5.5", features = ["decimal", "postgres", "runtime-tokio-rustls"] }
tokio = {version = "1.2", features = ["macros", "rt-multi-thread"]}
tokio-util = { version = "0.6.7", features = ["time"] }
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
uuid = "0.8.2"

[dev-dependencies]
rdkafka = "0.26.0"
