[package]
name = "order-manager"
version = "0.1.0"
authors = ["Sebastian Rollen <seb@overmu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#alpaca = {git = "ssh://git@github.com/Overmuse/alpaca.git", tag = "v0.4.0", default-features = false, features = ["rest", "ws"]}
alpaca = {git = "ssh://git@github.com/Overmuse/alpaca.git", tag = "v0.5.0", default-features = false, features = ["rest", "ws"]}
anyhow = "1.0.39"
async-trait = "0.1.48"
chrono = "0.4.19"
config = "0.10.1"
dotenv = "0.15"
env_logger = "0.8.3"
futures = "0.3.13"
log = "0.4.14"
rdkafka = {version = "0.26.0", features = ["ssl-vendored"]}
serde = "1.0.124"
serde_json = "1.0.64"
serde_plain = "0.3.0"
sqlx = {version = "0.5", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"]}
stream-processor = {path = "../stream-processor" }
tokio = {version = "1.2", features = ["macros", "rt-multi-thread"]}
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
