[package]
name = "order-manager"
version = "1.0.1"
authors = ["Sebastian Rollen <seb@overmu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpaca = {git = "ssh://git@github.com/Overmuse/alpaca.git", tag = "v0.6.0", default-features = false, features = ["rest", "ws"]}
anyhow = "1.0.39"
async-trait = "0.1.48"
bson = "2.0.0-beta"
chrono = "0.4.19"
config = "0.10.1"
dotenv = "0.15.0"
futures = "0.3.13"
kafka-settings = {git = "ssh://git@github.com/Overmuse/kafka-settings.git", tag = "v0.2.2" }
mongodb = "2.0.0-alpha"
serde = "1.0.124"
serde_json = "1.0.64"
stream-processor = { git = "ssh://git@github.com/Overmuse/stream-processor", tag = "v0.2.1" }
tokio = {version = "1.2", features = ["macros", "rt-multi-thread"]}
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
uuid = "0.8.2"

[dev-dependencies]
rdkafka = "0.26.0"
