apiVersion: v1
kind: ConfigMap
metadata:
  name: order-manager-cm
data:
  KAFKA__GROUP_ID: order-manager
  KAFKA__INPUT_TOPICS: overmuse-trades,position-intents
  DATABASE__NAME: ordermanagerdb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager-deployment
spec:
  selector:
    matchLabels:
      app: order-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
      - name: order-manager
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/order-manager:${IMAGE_TAG}
        env: 
          - name: DATABASE__URL
            valueFrom:
              secretKeyRef:
                name: mongo
                key: MONGO__URL
        envFrom:
        - secretRef:
            name: kafka
        - configMapRef:
            name: order-manager-cm
        - configMapRef:
            name: kafka-config-map
